#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/illuminate/foundation/helpers.php';

$app = new Illuminate\Foundation\Application(
	realpath(__DIR__)
);

$app->singleton(
	'Illuminate\Contracts\Console\Kernel',
	'Queue\Kernel'
);

$app->singleton(
	'Illuminate\Contracts\Debug\ExceptionHandler',
	'Queue\Handler'
);

$kernel = $app->make('Illuminate\Contracts\Console\Kernel');

$status = $kernel->handle(
	$input = new Symfony\Component\Console\Input\ArgvInput,
	new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
